# Generated by Django 4.2.7 on 2026-04-04 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biodiversity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodiversitymetric',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'Species'},
        ),
        migrations.RemoveField(
            model_name='observation',
            name='ai_result',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='habitat_type',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='weather_condition',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_preferences',
        ),
        migrations.AddField(
            model_name='alert',
            name='trigger_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='biodiversitymetric',
            name='endangered_species_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biodiversitymetric',
            name='evenness',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='biodiversitymetric',
            name='new_species_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='biodiversitymetric',
            name='simpson_index',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='biodiversitymetric',
            name='total_observations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='species',
            name='common_names',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='species',
            name='is_native',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('SD', 'Species Decline'), ('SI', 'Species Increase'), ('NS', 'New Species'), ('RE', 'Rare Species'), ('BD', 'Biodiversity Drop'), ('INV', 'Invasive Species')], default='BD', max_length=3),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('C', 'Critical'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='biodiversitymetric',
            name='shannon_index',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='biodiversitymetric',
            name='species_richness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='observation',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='observation',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biodiversity.species'),
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.CharField(choices=[('FA', 'Fauna (Animals)'), ('FL', 'Flora (Plants)'), ('FU', 'Fungi'), ('LI', 'Lichen'), ('AL', 'Algae'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('RAN', 'Forest Ranger'), ('RES', 'Researcher'), ('VOL', 'Volunteer'), ('ADM', 'Administrator')], default='VOL', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
