# Generated by Django 4.2.7 on 2026-04-04 16:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biodiversity', '0002_alter_biodiversitymetric_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at', '-severity']},
        ),
        migrations.AlterModelOptions(
            name='biodiversitymetric',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Biodiversity metrics'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name_plural': 'Species'},
        ),
        migrations.AddField(
            model_name='biodiversitymetric',
            name='calculation_method',
            field=models.CharField(default='Shannon-Wiener', max_length=100),
        ),
        migrations.AddField(
            model_name='biodiversitymetric',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='ai_model_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='observation',
            name='habitat_type',
            field=models.CharField(blank=True, choices=[('TF', 'Tropical Forest'), ('TMF', 'Temperate Forest'), ('BF', 'Boreal Forest'), ('MF', 'Mangrove Forest'), ('CF', 'Cloud Forest'), ('RF', 'Riparian Forest'), ('OT', 'Other')], max_length=3),
        ),
        migrations.AddField(
            model_name='observation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='weather_condition',
            field=models.CharField(blank=True, choices=[('CL', 'Clear/Sunny'), ('PC', 'Partly Cloudy'), ('CLD', 'Cloudy'), ('RN', 'Rainy'), ('FG', 'Foggy'), ('SN', 'Snowy'), ('WD', 'Windy')], max_length=3),
        ),
        migrations.AddField(
            model_name='species',
            name='class_name',
            field=models.CharField(blank=True, db_column='class', max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='confidence_threshold',
            field=models.FloatField(default=0.75, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='species',
            name='family',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='genus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='kingdom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='order',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='phylum',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='threat_factors',
            field=models.TextField(blank=True, help_text='Major threats to this species'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('SD', 'Species Decline'), ('SI', 'Species Increase'), ('NS', 'New Species'), ('RE', 'Rare Species Encountered'), ('BD', 'Biodiversity Drop'), ('BI', 'Biodiversity Increase'), ('INV', 'Invasive Species'), ('THR', 'Threat Detected')], max_length=3),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('C', 'Critical')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='biodiversitymetric',
            name='evenness',
            field=models.FloatField(default=0, help_text="Species evenness (Pielou's J)"),
        ),
        migrations.AlterField(
            model_name='biodiversitymetric',
            name='shannon_index',
            field=models.FloatField(default=0, help_text='Shannon-Wiener Diversity Index'),
        ),
        migrations.AlterField(
            model_name='biodiversitymetric',
            name='simpson_index',
            field=models.FloatField(default=0, help_text="Simpson's Diversity Index"),
        ),
        migrations.AlterField(
            model_name='biodiversitymetric',
            name='species_richness',
            field=models.IntegerField(default=0, help_text='Number of species observed'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='confidence_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='humidity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='image',
            field=models.ImageField(help_text='Photo of the species', upload_to='observations/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='location',
            field=models.CharField(help_text='Location description', max_length=500),
        ),
        migrations.AlterField(
            model_name='observation',
            name='notes',
            field=models.TextField(blank=True, help_text="Observer's notes"),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observation',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='biodiversity.species'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature in Celsius', null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.CharField(choices=[('FL', 'Flora (Plants)'), ('FA', 'Fauna (Animals)'), ('FU', 'Fungi'), ('LI', 'Lichen'), ('AL', 'Algae'), ('OT', 'Other')], default='FA', max_length=2),
        ),
        migrations.AlterField(
            model_name='species',
            name='common_names',
            field=models.TextField(blank=True, help_text='Other common names (comma-separated)'),
        ),
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the species'),
        ),
        migrations.AlterField(
            model_name='species',
            name='detection_count',
            field=models.IntegerField(default=0, help_text='Number of times detected'),
        ),
        migrations.AlterField(
            model_name='species',
            name='is_native',
            field=models.BooleanField(default=True, help_text='Is this species native to the area?'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(help_text='Common name of the species', max_length=200),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(help_text='Scientific/Latin name', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('RAN', 'Forest Ranger'), ('RES', 'Researcher'), ('VOL', 'Volunteer'), ('ADM', 'Administrator'), ('EDU', 'Educator')], default='VOL', max_length=3),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at'], name='biodiversit_created_15adf7_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'is_resolved'], name='biodiversit_alert_t_ba7a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'is_resolved'], name='biodiversit_severit_a3d43d_idx'),
        ),
        migrations.AddIndex(
            model_name='biodiversitymetric',
            index=models.Index(fields=['-date'], name='biodiversit_date_bfe985_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['-timestamp'], name='biodiversit_timesta_db1dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['species', 'timestamp'], name='biodiversit_species_f39f81_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['observer', 'timestamp'], name='biodiversit_observe_ad329c_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['latitude', 'longitude'], name='biodiversit_latitud_398e97_idx'),
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['name'], name='biodiversit_name_b4e344_idx'),
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['scientific_name'], name='biodiversit_scienti_c90f83_idx'),
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['category', 'conservation_status'], name='biodiversit_categor_3beb93_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='biodiversit_user_id_891d05_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role', 'is_verified'], name='biodiversit_role_78e9a5_idx'),
        ),
    ]
